<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>All Products</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>628f76b6-b6ae-4a66-9a2e-de899213bb9e</testSuiteGuid>
   <testCaseLink>
      <guid>c9b31589-4b51-4b0f-b948-b5e96c7fd019</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Product Overview/TC08_Check_display_info_product_01</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7a152d8-9305-4171-97ba-ac3df487f683</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>288a97cd-d160-4049-91f9-c3950f6b29af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e7653e3-dbc1-4c74-a7df-1e66289afa60</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4dfde1be-dc80-43bc-97bb-96eaeb884f71</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Product Overview/TC09_Check_display_info_product_02</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a727f074-c242-4503-a5ef-c04c074e62a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c3fae12-fb77-4169-8013-d1aab5e4b7a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f08f41bc-bf12-4eeb-87e3-c2c1fc65414f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9f6501ef-0243-4fc9-ba83-1c1b8641c62e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Product Overview/TC10_Check_display_info_product_03</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d00be674-f943-49db-b01f-4176085bea92</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d554b065-b6c9-4180-8c34-b99d4c2588bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1defd29-bfc2-4c3f-8e2d-e0ac5dcc2eae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d38c7715-c577-407d-bef4-012725cafa32</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Product Overview/TC11_Check_display_info_product_04</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>313e294c-2ff7-4c0f-93d6-59ccc279e9ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26b1f7ea-3ad8-4503-b561-b4a4ee6c7bd1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ac18b30-6838-48b1-a81d-fd8e67d7a515</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3c76f112-eee2-438e-980c-d3ba23cb581a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Product Overview/TC12_Check_display_info_product_05</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fccdebdd-cc3f-47d9-9322-a3caa6acc0bb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03cddbdd-0095-491a-a4c2-e2415ec4baa1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4de1a842-b3cc-497a-b4ce-f269e4a0e1c9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0f2e7bae-3ef7-4c90-9927-b65ed1665e9e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Product Overview/TC13_Check_display_info_product_06</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3ef0ab4-0618-40b6-811f-a42e5f6f4a93</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af2fcf33-fba3-47b7-a070-1ac7f86fa243</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68006b25-488c-4bbe-b572-5670822fc4bf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>00cdda9b-0745-4fa5-8f57-e43a649c9976</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Product Overview/TC14_Check_display_info_product_07</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d031dfb4-0d6d-4483-9e1f-b87a1ef06c1c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>704009a4-4883-4bbf-97e8-cbd9719a8a72</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e219bef3-b878-450e-9119-a6e831bd5f93</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b816d75e-25aa-459f-8c61-953d33691f66</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Product Overview/TC15_Check_display_info_product_08</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc6ac6a0-c959-4e38-8185-285208a302d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d7fe3d3-d95d-4d01-b514-73db29b6e658</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebbd0f91-548d-417d-99af-1884d0c0401c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c58a10a8-0e24-4b11-a57d-bce47667a562</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Product Overview/TC16_Check_display_info_product_09</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ad6654e-e5f6-423b-a23a-3213a3aaad9d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5b71d58-d65d-4d67-9ada-8004cc2dc954</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b12d53f9-36d3-4eae-8f61-68b77888a2f4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>528c23d9-871d-4d93-ac97-32feb5035c63</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Product Overview/TC17_Check_display_info_product_10</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfa748fd-21b8-4b7c-8f53-f9911623e117</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8235a70c-77f0-4f68-87ed-bf7ee1b797d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47342f96-4aee-451e-8b26-2609908f8b22</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
