<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Check_out</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>cc5c0675-9a6e-4de1-b552-cd424bcc10a1</testSuiteGuid>
   <testCaseLink>
      <guid>e526e6a4-248a-4a6c-9166-3fe20d66e6be</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Check out/TC49_Logged_out_Checkout</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d5aa6a9-3204-4c9d-9d01-c5f92d1d47ca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>40e2cd72-3f44-4089-94ba-0234cacdb871</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Check out/TC50_Logged_in_Checkout</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2c022ac-5db7-41c6-ac3c-d7433d1fcbf4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ed93746-9f7b-422b-a2c8-920cfa74426a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7d47014-1fc0-4da8-aa22-1c265ad84a56</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
