<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Sign in</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>673dcf5c-8b6e-42d6-80ee-b762111e4ab6</testSuiteGuid>
   <testCaseLink>
      <guid>3348acb7-5ea0-42a2-a8b4-e0c2b6c6fcc9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sign in/TC01_Fill_wrong_username_password_format</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51de439c-6908-49c0-aec3-f3cfa7c1c64e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2df69bbd-f291-457b-b830-54d2042ff445</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ed9fb8c4-521e-4b16-b3c9-1752edbce9e9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sign in/TC02_Login_with_blank_username_password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>c48fcb32-cea6-4b33-8357-b9f9494210e7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sign in/TC03_Login_with_incorrect_username_password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6014a061-4a88-4293-99dc-410f7689d2b1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eec0973b-5041-4b57-b9c3-b71ff5166dd8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>727d7f65-f789-4609-9bd2-55a68704d1e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sign in/TC04_Login_with_correct_username_password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb9b346e-42df-469e-bc64-f2d216879e63</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70ae92ea-d6f3-4684-8b18-0ca07adea498</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ee4ee5f3-2212-4c3d-9a62-fcca34f2169d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sign in/TC05_Login_page_success_via_Account_button</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9907d71b-9269-48cc-9de3-a7452d3c16f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7eb2625-798c-459f-a25e-dd95f35bd01d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
