<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Sign up</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>7fd6bbf3-a074-4441-ae45-ff45f0b0b16c</testSuiteGuid>
   <testCaseLink>
      <guid>1590fa45-09e2-4ad9-8a39-8d4c61210d04</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Sign up/TC18_Fill_wrong_email_format</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70e1fded-e571-43df-9c58-eed100ec230d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20e600b4-d0d7-4b64-bb4f-56a480d2494f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1a01bee7-7689-4c7c-9985-389a630e0a60</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Sign up/TC19_Fill_wrong_password_rule</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a86ff6b0-aacc-407b-b4b7-e31f866e080a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7882fef2-4753-432f-9c50-e1329559cbf3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c01d4a48-b9ed-49c2-b204-9c50c3641011</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Sign up/TC20_Fill_wrong_verify_password_rule</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd185ba6-f9b4-42c0-a353-9d197b323927</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fdfdc289-8c03-4efb-8a22-3cdb374591a1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a7ea6343-1d55-4fff-bbca-29bb71000cf7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Sign up/TC21_Leave_all_empty_info</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
