<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Search</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>804e70aa-49e8-45f4-9fec-69e23a5ddea4</testSuiteGuid>
   <testCaseLink>
      <guid>da452f9b-76ee-4c73-8c8d-e332671b6a9a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Search/TC22_Search_and_check_detail_info_product_01</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f186022e-bc26-48e2-95c1-61bc744a44d6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e82e49c-c55f-4134-8065-306183502297</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99d19c75-6e00-46a7-a82b-688c6587259f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b3d9d2b1-9376-4ffa-a221-9c50a4f1cb61</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Search/TC40_Search_and_check_detail_info_product_02</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ed5ec47-fce0-4e75-b748-1cc31daedcad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c25047a9-4c98-4d8b-af3a-a3f16731520c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ac25ec9-7143-40a0-88be-0308e9083a6b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e320285e-7965-46b8-9110-2bf737079ea0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Search/TC41_Search_and_check_detail_info_product_03</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c95b6313-152f-4b19-bd59-cfff813bbaa2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3d3b85a-19af-44db-ab49-78b2031411c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0822c5fd-40d6-478c-a35d-e1f45264ec6b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3e16b482-5074-498c-9c45-68e9485f0193</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Search/TC42_Search_and_check_detail_info_product_04</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6d99369-1e52-4b0f-857b-62347e6616b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3742ef7-0598-4e6b-8b8c-3283570b54f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e5f6bb5-7e6b-423a-8821-e4c679b89b46</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1c0c8e9d-45b7-461a-86ee-ce5fe61e26d0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Search/TC43_Search_and_check_detail_info_product_05</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79480904-8ba4-49c0-bd71-5515d63a8137</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0882c88d-4713-4b8c-a77f-ab18c18b69ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d87a4091-ab39-49f7-b7a8-7b3b22195eba</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2f621fff-079c-4a3d-90d1-cf5e75e0022e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Search/TC44_Search_and_check_detail_info_product_06</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>712bbd19-570d-45b5-b405-f3b6646d4d8d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cbba370c-95c0-47cc-b6aa-e49e186d6936</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ecdf577a-e8c4-487e-ad44-9212893bc9b8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9c5f0558-8d22-436f-b25a-cf99e6fda71f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Search/TC45_Search_and_check_detail_info_product_07</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e45176e4-44c9-418b-acb2-f28f9aca0a4a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef420da5-c269-47e3-b88d-594e0480bbdb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54469f13-249b-4860-ac3b-e698a846f9db</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c92bd081-d363-4642-95c7-1e317b0dc3d5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Search/TC46_Search_and_check_detail_info_product_08</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b82daf10-c7d9-41f5-978e-f114a1d6d771</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71d1b79f-d69d-4ef8-99ed-a319de79eaff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eff49213-d9bd-4f87-86ad-068e8b4ccbc3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>40a9ea4d-a55b-4a1a-aef2-ebf0e2624d82</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Search/TC47_Search_and_check_detail_info_product_09</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3dc4be26-7f57-4d64-b43c-0b1b3b780b0c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc88f402-dc02-41d2-ad90-1d8b17fb71a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ae40b39-1388-46bb-bddc-12d970b322ff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>517d13b9-b99b-40a8-87a0-16d23c18f604</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Search/TC48_Search_and_check_detail_info_product_10</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>efbc8def-ad10-4d9f-8ea6-52c6cef1d31d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90fa846d-5032-4cbe-befa-adb26f0aacc0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f9eaadf-77ec-46d3-a24a-0a3ea46d843b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
