<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Header_menu</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>ba946054-ab04-4fb7-9bca-899058ecabd0</testSuiteGuid>
   <testCaseLink>
      <guid>5d7f75a8-555a-44a8-ba6e-b4b0ab57d758</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Filter/TC23_HeaderMenu_Women_product_type_Basics</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27621b1c-787c-4ddc-b25c-e4f31cc8d031</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a51a563-42c6-42cd-a5bc-8e121fc8ac2e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f30b705f-0bba-4b0f-b668-07414ef7b90a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>711b251b-152a-431d-abbc-77e86c78db42</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Filter/TC24_HeaderMenu_Women_product_type_Blazer</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9197adb2-0747-4235-8769-1a40c0281dcf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9edf8abd-2bb1-4ca1-9732-b22bed14fd8f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1100415a-70da-4281-81a3-41376b129ef5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5349a8c0-76df-46b6-8041-e0394c60e1e7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Filter/TC25_HeaderMenu_Kids_product_type_Girl</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f4a51ea-f7f8-42d4-9d8c-8587605dc95e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>484b1d9f-953b-496e-aee1-c7a676f2aa41</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0aeb11d-89ea-4de9-a77b-849eb249b78e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2b02ad99-7e4d-4073-8629-6be7dc7251f8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Filter/TC26_HeaderMenu_Kids_product_type_Boy</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31531bda-8604-4273-98e1-35887c7c416d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>949a5a72-6bf6-4bc6-9238-57b526863de7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1afd1502-7638-46de-ae0c-d01241fa8e67</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7abb6b2c-a3af-40ec-afae-d1b539f50ed9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Filter/TC27_HeaderMenu_Men_product_type_Knitwear</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f279d50-e0c4-4c0c-bcab-ab1bd3f9d710</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6eca748d-e0cc-4c11-8089-8b6fbe92a10d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c039d16d-d39a-4553-bee8-0ae7563ac743</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>336630da-0da7-418e-94d5-3a496c9913f8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Filter/TC28_HeaderMenu_Men_product_type_Jeans</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>962818bc-5c21-49a0-9a31-e9e29b09eccd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9118a268-401e-45f4-b53e-162f40dfcb92</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8776df41-c910-4668-97ca-0cc5d8b2e40c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a5e74ced-015f-4e6b-87ed-49bcbe753967</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Filter/TC29_HeaderMenu_Men_product_type_Jackets</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ec882e8-413c-4f59-a338-4dd97431fe78</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b3e48a4-dd61-44a2-bec0-03535de7948c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1762556-f980-4ae5-99a9-d07131cdc3cb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ebb5a318-979d-49e9-a724-c4aa57a65a75</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Filter/TC30_HeaderMenu_All_products_01</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f51739d-2b61-4d5d-b5d5-5c4a44a7b5ae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c3d79c59-7da2-44b5-904d-e1f5daac4f67</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Filter/TC31_HeaderMenu_All_products_02</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c679d037-bcc4-4f4b-b2aa-5a8272e624fa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>965461d4-3fc9-4fae-a16e-33b025aa17fc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Filter/TC32_HeaderMenu_All_products_03</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38fe703b-f502-43f7-99d5-f6bf7d737da7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0f1f40ee-e192-4358-a45a-31ea012f9ada</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Filter/TC33_HeaderMenu_All_products_04</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>37d4caee-b59f-4b8c-b605-59544652f64c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4ec98f8d-3f80-462d-8bb7-79ca61ca5647</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Filter/TC34_HeaderMenu_All_products_05</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbfc0dba-3fd5-4915-8956-2f0c16dcced6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b1d65512-d143-4d05-a686-273f9acbe06f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Filter/TC35_HeaderMenu_All_products_06</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c484cc4-7f8d-4d88-a98d-763754a89b39</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8b4c69b8-6d68-4a08-af85-d3712283aa46</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Filter/TC36_HeaderMenu_All_products_07</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3196ed26-6403-4180-bacb-6ce1e47ae596</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>96ef84db-50b1-4763-8229-a57ff9f6fb4d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Filter/TC37_HeaderMenu_All_products_08</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1830ef4e-d036-49a8-80f6-83f65298c702</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>60ebb934-1fdd-421f-b948-d96befabdd07</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Filter/TC38_HeaderMenu_All_products_09</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3afbd095-5615-416c-9abb-1832477b01da</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7dd2dc31-31d0-482c-9a3c-dd48537b6d6c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Filter/TC39_HeaderMenu_All_products_10</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba790972-78c7-4fc8-abb8-eec685a50ebd</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
