<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Header_menu_All</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>222bd981-7c6c-4eae-8b25-86dac8e65c1f</testSuiteGuid>
   <testCaseLink>
      <guid>ce5e21f6-1a02-4419-bcf4-6266b557c20d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Filter/TC30_HeaderMenu_All_products_01</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f51739d-2b61-4d5d-b5d5-5c4a44a7b5ae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>271944e2-b6c1-4386-9260-58c89a97c4eb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Filter/TC31_HeaderMenu_All_products_02</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c679d037-bcc4-4f4b-b2aa-5a8272e624fa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>87dbf064-799b-49e9-9e13-17597ca5a580</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Filter/TC32_HeaderMenu_All_products_03</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38fe703b-f502-43f7-99d5-f6bf7d737da7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d3552f50-fe76-454c-b73a-571a031ea5bd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Filter/TC33_HeaderMenu_All_products_04</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>37d4caee-b59f-4b8c-b605-59544652f64c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d92fbb2e-c666-49fb-bec5-57f037e4477e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Filter/TC34_HeaderMenu_All_products_05</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbfc0dba-3fd5-4915-8956-2f0c16dcced6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9ad596bf-7480-4481-becc-00a1439333f0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Filter/TC35_HeaderMenu_All_products_06</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c484cc4-7f8d-4d88-a98d-763754a89b39</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>00d47a9a-5130-4f9e-999b-585b9f067045</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Filter/TC36_HeaderMenu_All_products_07</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3196ed26-6403-4180-bacb-6ce1e47ae596</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>186bc716-5177-4e3c-8c19-b07d18ad1712</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Filter/TC37_HeaderMenu_All_products_08</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1830ef4e-d036-49a8-80f6-83f65298c702</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>95f7b6f4-05ca-4981-829a-24b296c80148</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Filter/TC38_HeaderMenu_All_products_09</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3afbd095-5615-416c-9abb-1832477b01da</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4db9086d-5478-4124-846a-0149fccf08fb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopping Cart/Filter/TC39_HeaderMenu_All_products_10</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba790972-78c7-4fc8-abb8-eec685a50ebd</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
